bracketSpacing: true
printWidth: 120
singleQuote: false
tabWidth: 2
plugins:
  - "@trivago/prettier-plugin-sort-imports"

overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
  - files: "*.ts"
    options:
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      parser: "typescript"
