[profile.default]
src = "contracts"
test = 'test'
script = 'script'
out = "out"
libs = ["node_modules"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 125
evm_version = "cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default.fuzz]
# seed = "0x00"

[profile.default.invariant]
runs = 10
depth = 100
fail_on_revert = true
show_metrics = true
